- name: This playbook will install, configure and deploys a web page in nginx
  hosts: all
  vars:
    proxy_configuration:
       http_proxy: http://10.19.16.165:8080
       https_proxy: http://10.19.16.165:8080
  tasks:
    - name: Install nginx web server in Ubuntu
      apt: name=nginx state=latest update_cache=yes
      #env: "{{proxy_configuration}}"

    - name: Start the nginx server
      command: service nginx start
